/*=============================================================================
	DLAACopyTexture.usf: Write texture as-is to render target.
=============================================================================*/

#include "/Engine/Private/Common.ush"

Texture2D InTexture;
SamplerState InTextureSampler;

void DLAACopyTexturePixelShader(
	FScreenVertexOutput Input,
	out float4 OutColor : SV_Target0
	)
{
	// Copy texture
	OutColor = float4(InTexture.Load(Input.Position.xyz).rgb, 1.0);
}
